version: "3.8"

services:
  nostr-relay:
    image: scsibug/nostr-rs-relay:latest
    ports:
      - "8080:8080"

  dvm-service-provider:
    build:
      context: .
      dockerfile: Dockerfile
    command: dvm_service_provider
    env_file: .env
    volumes:
      - ./config:/usr/src/askeladd/config
    depends_on:
      nostr-relay:
        condition: service_started
    environment:
      - APP_SUBSCRIBED_RELAYS=ws://nostr-relay:8080

  dvm-customer:
    build:
      context: .
      dockerfile: Dockerfile
    command: dvm_customer
    env_file: .env
    volumes:
      - ./config:/usr/src/askeladd/config
    depends_on:
      nostr-relay:
        condition: service_started
      dvm-service-provider:
        condition: service_started
    environment:
      - APP_SUBSCRIBED_RELAYS=ws://nostr-relay:8080
