//! Fibonacci proving, reimplemented on top of raw STWO components.
//!
//! STWO dropped its simple `examples::fibonacci` in favor of the wide
//! variant; this module keeps a minimal single-column Fibonacci AIR alive
//! because it is the smallest honest example of "prove a computation,
//! verify it anywhere" — which is the whole point of Askeladd.

use self::component::FibonacciComponent;
use crate::StwoResult;
pub mod air;
pub mod component;
pub mod multi_fibonacci;

use air::FibonacciAir;
use num_traits::One;
use stwo_prover::core::backend::cpu::CpuCircleEvaluation;
use stwo_prover::core::channel::{Blake2sChannel, Channel};
use stwo_prover::core::fields::m31::BaseField;
use stwo_prover::core::fields::{FieldExpOps, IntoSlice};
use stwo_prover::core::poly::circle::{CanonicCoset, CircleEvaluation};
use stwo_prover::core::poly::BitReversedOrder;
use stwo_prover::core::prover::{ProvingError, StarkProof, VerificationError};
use stwo_prover::core::vcs::blake2_hash::Blake2sHasher;
use stwo_prover::core::vcs::blake2_merkle::Blake2sMerkleHasher;
use stwo_prover::trace_generation::{commit_and_prove, commit_and_verify};
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    // Use `js_namespace` here to bind `console.log(..)` instead of just
    // `log(..)`
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

macro_rules! console_log {
    // Note that this is using the `log` function imported above
    ($($t:tt)*) => (log(&format_args!($($t)*).to_string()))
}

/// A self-contained Fibonacci prover/verifier: the AIR plus its public statement.
#[derive(Clone)]
pub struct Fibonacci {
    pub component: FibonacciComponent,
    pub air: FibonacciAir,
}

impl Fibonacci {
    pub fn new(log_size: u32, claim: BaseField) -> Self {
        let component = FibonacciComponent::new(log_size, claim);
        let air = FibonacciAir {
            component: component.clone(),
        };
        Self { component, air }
    }

    /// The Fibonacci-squared trace: `a₀ = 1, a₁ = 1, aₙ₊₂ = aₙ² + aₙ₊₁²`.
    pub fn get_trace(&self) -> CpuCircleEvaluation<BaseField, BitReversedOrder> {
        // Trace.
        let trace_domain = CanonicCoset::new(self.component.log_size);
        let mut trace = Vec::with_capacity(trace_domain.size());

        // Fill trace with fibonacci squared.
        let mut a = BaseField::one();
        let mut b = BaseField::one();
        for _ in 0..trace_domain.size() {
            trace.push(a);
            let tmp = a.square() + b.square();
            a = b;
            b = tmp;
        }

        // Returns as a CircleEvaluation.
        CircleEvaluation::new_canonical_ordered(trace_domain, trace)
    }

    /// Generates a STARK proof that the trace ending at `claim` satisfies the AIR.
    pub fn prove(&self) -> Result<StarkProof<Blake2sMerkleHasher>, ProvingError> {
        let channel = &mut Blake2sChannel::new(Blake2sHasher::hash(BaseField::into_slice(&[self
            .component
            .claim])));
        let trace = vec![self.get_trace()];
        commit_and_prove(&self.air, channel, trace)
    }

    /// Verifies a proof generated by [`Fibonacci::prove`].
    pub fn verify(&self, proof: StarkProof<Blake2sMerkleHasher>) -> Result<(), VerificationError> {
        let channel = &mut Blake2sChannel::new(Blake2sHasher::hash(BaseField::into_slice(&[self
            .air
            .component
            .claim])));
        commit_and_verify(proof, &self.air, channel)
    }
}

#[wasm_bindgen]
pub fn prove_and_verify_fib(log_size: u32, claim: u32) -> StwoResult {
    console_log!(
        "Starting prove_and_verify with log_size: {}, claim: {}",
        log_size,
        claim
    );
    let fib = Fibonacci::new(log_size, BaseField::from(claim));

    match fib.prove() {
        Ok(proof) => {
            console_log!("Proof generated successfully");
            let serialized = match serde_json::to_string(&proof) {
                Ok(s) => s,
                Err(e) => {
                    return StwoResult {
                        success: false,
                        message: format!("Failed to serialize proof: {:?}", e),
                    }
                }
            };

            match fib.verify(proof) {
                Ok(_) => {
                    console_log!("Proof verified successfully");
                    StwoResult {
                        success: true,
                        message: serialized,
                    }
                }
                Err(e) => {
                    console_log!("Proof verification failed: {:?}", e);
                    StwoResult {
                        success: false,
                        message: format!("Proof verification failed: {:?}", e),
                    }
                }
            }
        }
        Err(e) => {
            console_log!("Proof generation failed: {:?}", e);
            StwoResult {
                success: false,
                message: format!("Proof generation failed: {:?}", e),
            }
        }
    }
}

#[wasm_bindgen]
pub fn verify_stark_proof_fib(log_size: u32, claim: u32, stark_proof_str: &str) -> StwoResult {
    console_log!(
        "Starting verify_stark_proof with log_size: {}, claim: {}",
        log_size,
        claim
    );
    console_log!("Received proof string length: {}", stark_proof_str.len());

    let fib = Fibonacci::new(log_size, BaseField::from(claim));

    let stark_proof: Result<StarkProof<Blake2sMerkleHasher>, serde_json::Error> =
        serde_json::from_str(stark_proof_str);

    match stark_proof {
        Ok(proof) => {
            console_log!("Proof deserialized successfully");
            match fib.verify(proof) {
                Ok(()) => {
                    console_log!("Proof verified successfully");
                    StwoResult {
                        success: true,
                        message: "Proof verified successfully".to_string(),
                    }
                }
                Err(e) => {
                    console_log!("Proof verification failed: {:?}", e);
                    StwoResult {
                        success: false,
                        message: format!("Proof verification failed: {:?}", e),
                    }
                }
            }
        }
        Err(e) => {
            console_log!("Failed to deserialize proof: {:?}", e);
            StwoResult {
                success: false,
                message: format!("Failed to deserialize proof: {:?}", e),
            }
        }
    }
}
